

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : projlab
//  @ File Name : Entity.java
//  @ Date : 2021. 03. 19.
//  @ Author : Levente Vigh
//
//




public abstract class Entity {
	protected Asteroid position;
	
	public Entity() {
		
	}
	
	public Entity(Asteroid a) {
		position = a;
	}

	public void die() {
		position.removeEntity(this);
		position = null;
	}
	
	public void drill() {
		position.getDrilled();
	}
	
	public abstract void move();
	
	public abstract void solarStormEffect();
	
	public abstract void explosionEffect();
	
	public void step() throws Exception { }
	
	public void setPosition(Asteroid a) throws Exception {
		if(null == a)
			throw new Exception("Argument passed to Entity.setPosition(...) is null");
		position = a;
	}
}
