//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Astronaut.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Astronaut extends Entity {
	private Gate gates:;
	private Material collectedMaterials:;
	private Game game;
	public void craftRobot() {
	}
	
	public void craftGate() {
	}
	
	public void mine() {
	}
	
	public void solarStormEffect() {
	}
	
	public void deployGate() {
	}
	
	public void step() {
	}
	
	public void explosionEffect() {
	}
	
	public void putMaterialInAsteroid() {
	}
}
