//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BillOfMaterial.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class BillOfMaterial {
	private Collection<Material> current;
	protected void isNeeded(Material m) {
	}
	
	public void reset() {
	}
	
	public Collection<Material> checkInventory(Collection<Material> inv) {
	}
}
