//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BillCreator.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class BillCreator {
	public BillOfMaterial createRobotBill() {
	}
	
	public BillOfMaterial createGateBill() {
	}
	
	public BillOfMaterial createGameWinningBill() {
	}
}
