//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Carbon.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Carbon extends Material {
	private int getID() {
	}
}
