//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Entity.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public abstract class Entity {
	private Asteroid position;
	public void die() {
	}
	
	public void drill() {
	}
	
	public void move() {
	}
	
	public void solarStormEffect() {
	}
	
	public void explosionEffect() {
	}
	
	public void step() {
	}
}
