import java.util.ArrayList;
import java.util.Collection;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : projlab
//  @ File Name : Entity.java
//  @ Date : 2021. 03. 22.
//  @ Author : Levente Vigh
//
//




public abstract class Entity {
	//az aszteroida amin az entitas all
	protected Asteroid position;
	
	public Entity() { }
	
	public Entity(Asteroid a) {
		position = a;
	}

	//amikor meghal lekerul az aszteroidarol
	public void die() {
		Logger.call("Enity.die()","");
		
		position.removeEntity(this);
		position = null;
		
		Logger.ret("");
	}
	
	//az entitas megfurja az aszteroidat amin eppen all
	public void drill() {
		Logger.call("Enity.drill()","");
		
		position.getDrilled();

		Logger.ret("");	
	}

	//aszteroidak kozott mozog/teleportal
	public abstract void move();
	//napviharban milyen hatas eri az entitast
	public abstract void solarStormEffect();
	//robbanas milyen hatasssal van az entitasra
	public abstract void explosionEffect();
	
	//egy lepest vegrehajt az entitas
	public void step() throws Exception { Logger.call("Enity.step()","");  Logger.ret(""); }
	
	public void setPosition(Asteroid a) throws Exception {
		Logger.call("Enity.setPosition()", "Asteroid a: " + a.toString());
		
		if(null == a)
			throw new Exception("Argument passed to Entity.setPosition(...) is null");
		position = a;

		Logger.ret("");
	}

	public Collection<Material> getInventory() {
		return new ArrayList<Material>();
	}
}
