import java.awt.List;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.concurrent.ThreadLocalRandom;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Game {
	private Collection<Asteroid> asteroidField;
	//TODO majd késõbb
	private WindowHandler windowHandler;
	// a következõ kettõ nem muszáj de szerintem hasznos
	private Collection<Robot> robots;
	private Collection<Astronaut> astronauts;
	/*
	public void start() {
		//segéd változók:
		//aszteroidaöv mérete
		int asteroidfieldsize = 50;
		//asztronauták száma
		int astronautcount = 5;
		//randomhoz
		int randomNum;
		//összes materialbol mennyi kell a gyõzelemhez
		int materialsToWin = 3;
		//mennyi material van osszesen
		int materialcount = 4;
		
		
		//aszteroidaöv készítés:
		for(int i = 0; i < materialsToWin; i++) {
			//ice, iron, carbon, uranium mindenbõl 3, összesen 12
			asteroidField.add(new Asteroid(new Ice()));
			asteroidField.add(new Asteroid(new Iron()));
			asteroidField.add(new Asteroid(new Carbon()));
			asteroidField.add(new Asteroid(new Uranium()));
		}
		
		for(int i = 0; i < asteroidfieldsize - materialsToWin * materialcount; i++) {
			//maradék 38 random igy osszsesen 50
			//random szám 1-4 között
			randomNum = ThreadLocalRandom.current().nextInt(1, materialcount + 1);
			if(randomNum == 1) asteroidField.add(new Asteroid(new Ice()));
			else if(randomNum == 2) asteroidField.add(new Asteroid(new Iron()));
			else if(randomNum == 3) asteroidField.add(new Asteroid(new Carbon()));
			else if(randomNum == 4) asteroidField.add(new Asteroid(new Uranium()));
			else {System.out.println("Hiba a random szammal");}
			
		}
		System.out.println("Az aszteroidák elkészültek");
		
		//szomszédossságok létrehozása
		//TODO algoritmus a szomszédságok kialakítására javítani talán
		
		for (Asteroid a : asteroidField) {
			//ha kevés szomszédja van 3-nál kevesebb
			if(a.getNeighbours().size < 3) {
			
				//3 szomszédság hozzáadása
				for(int y = 0; y < 3; y++) {
					//Random szám generálása
					randomNum = ThreadLocalRandom.current().nextInt(0, asteroidField.size() + 1);
					boolean same = false;
					//megnézni van e már ilyen szomszédja
					for(Place p : a.getNeighbours()) {
						if(p.equals(((ArrayList<Asteroid>) asteroidField).get(randomNum))) {
							same = true;
						}
					}
					//ha nincs ilyen szomszédja
					if(same == false){
						//szomszédság  beállítása
						a.addNeighbour(((ArrayList<Asteroid>) asteroidField).get(randomNum));
						((ArrayList<Asteroid>) asteroidField).get(randomNum).addNeighbour(a);
					}
				}
			}
		}		
		System.out.println("Az aszteroidak egymas szomszedai.");
		System.out.println("Az aszteroidov elkeszult.");
		
		//asztronauták készítése
		for (int i = 0; i < astronautcount; i++) { 
			astronauts.add(new Astronaut());
		}
		System.out.println("Az asztronautak utra keszen.");
		
		//asztronauták lerakása random aszteroidákra
		for (int i = 0; i < astronauts.size(); i++) { 		      
			randomNum = ThreadLocalRandom.current().nextInt(0, asteroidField.size() + 1);
			((ArrayList<Asteroid>) asteroidField).get(randomNum).addEntity(((ArrayList<Astronaut>) astronauts).get(i));;
			
	      }   		
		System.out.println("Az asztronautak megerkeztek az aszteroidaovbe");
	}
	*/
	
	public void step() {
		
		//Minden astronautára meghivjuk a step()
		for(Astronaut a : astronauts) {
			try{
				a.step();
			} catch(Exception ex) {
				ex.printStackTrace();
			}
		}
		
		
		System.out.println("Leptek a telepesek.");
		
		//Minden robotra meghivjuk a step()
		for(Robot r : robots) {
			r.step();
		}
		System.out.println("Leptek a robotok.");
		
		//ha entitásoknak egy aszteroidán megvan a raktárukba az összes nyersanyag vége
		if(checkGameState() == false) end();
		
	}
	
	private void end() {
		//TODO majd késõbb
		
		asteroidField.clear();
		astronauts.clear();
		robots.clear();
		
		System.out.println("A jatek vegetert");
	}
	
	//true ha megy a játék, false ha nem
	private boolean checkGameState() {
		
		//bill készítése
		BillOfMaterial bill = new BillCreator().createGameWinningBill();
		//összes aszeroidára
		for (Asteroid a : asteroidField) {
			ArrayList<Material> onAsteroid = new ArrayList<>();
			//TODO összes entitás az aszteroidán
			
		//	bill.checkInventory(inv);
		}
		//return false;
		return true;
	}
	
	public void solarStorm() {
		//összes aszteroidára solarStorm()
		for (Asteroid a : asteroidField) { 		      
	          a.solarStorm();		
	      }
	}
	
	public void nearSun() {
		//összes aszteroidára checkNearSun()
		for (Asteroid a : asteroidField) { 		      
	          a.checkNearSun();		
	      }
	}
	
	//a megadott aszteroidát kiszedi az aszteroidák közül
	public void removeFromAsteroidField(Asteroid a) {
		
		this.asteroidField.remove(a);
		System.out.println("Egy aszteroida megsemmisult");
	}
}
