//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Game.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Game {
	private Asteroid asteroidField:;
	private WindowHandler windowHandler;
	private Robot robots;
	public void start() {
	}
	
	public void step() {
	}
	
	private void end() {
	}
	
	private void checkGameState() {
	}
	
	public void solarStorm() {
	}
	
	public void nearSun() {
	}
	
	public void removeFromAsteroidField(Asteroid a) {
	}
}
