//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Gate.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Gate extends Place {
	private boolean isActive;
	private Asteroid position;
	private Gate otherEnd: Gate;
	private Asteroid position;
	private Gate otherEnd: Gate;
	public void setPosition(Asteroid a) {
	}
	
	public void setOtherEnd(Gate g) {
	}
	
	public void explode() {
	}
	
	public void enable() {
	}
	
	public void disable() {
	}
	
	public Place getPosition() {
	}
}
