//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Material.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public abstract class Material {
	private Asteroid asteroid;
	public void mined() {
	}
	
	public void nearSunEffect() {
	}
	
	protected int getID() {
	}
	
	public bool isSameType(Material m) {
	}
}
