import java.util.Vector;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Place.java
//  @ Date : 2021. 03. 19.
//  @ Author : Mate Simko
//
//


public class Place {
	
	/**
	 * A Place-en levo entitasokat tarolo lista.
	 */
	protected Vector<Entity> entities;
	/**
	 * A Place szomszedait tarolo lista.
	 */
	protected Vector<Place> neighbours;
	
	/**
	 * Konstruktor
	 */
	public Place() {
		entities = new Vector<Entity>();
		neighbours = new Vector<Place>();
	}
	
	/**
	 * Entitas felveteleert felelos fuggveny
	 * @param e Entias
	 */
	public void addEntity(Entity e) {
		Logger.call("Place.addEntity", " Entity = " + e.toString());
		entities.add(e);
		Logger.ret("");
	}
	
	/**
	 * Entitas torleseert felelos fuggveny
	 * @param e Entias
	 */
	public void removeEntity(Entity e) {
		Logger.call("Place.removeEntity", " Entity = " + e.toString());
		for(int i = 0; i < entities.size(); i++) {
			if(entities.elementAt(i).equals(e)) {
				entities.remove(i);
			}
		}
		Logger.ret("");
	}
	
	/**
	 * Robbanas fuggveny
	 * Szol az osszes rajta levo entitasnak es szomszednak a robbanasrol
	 */
	public void explode() {
		Logger.call("Place.explode", "");
		for(int i = 0; i < entities.size(); i++) {
			entities.elementAt(i).explosionEffect();
		}
		for(int i = 0; i < neighbours.size(); i++) {
			neighbours.elementAt(i).removeNeighbour(this);
		}
		Logger.ret("");
	}
	
	/**
	 * Szomszed felveteleert felelos fuggveny
	 * @param p Szomszed
	 */
	public void addNeighbour(Place p) {
		Logger.call("Place.addNeighbour", " Place = " + p.toString());
		neighbours.add(p);
		Logger.ret("");
	}
	
	/**
	 * Szomszed torleseert felelos fuggveny
	 * @param p Szomszed
	 */
	public void removeNeighbour(Place p) {
		Logger.call("Place.removeNeighbour", " Place = " + p.toString());
		for(int i = 0; i < neighbours.size(); i++) {
			if(neighbours.elementAt(i).equals(p)) {
				neighbours.remove(i);
			}
		}
		Logger.ret("");
	}
}
