
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Timer.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Timer {
	private Game game;
	
	private void tick() throws Exception {
		game.step();
	}
	
	public void start() throws Exception {
		//long startTime = System.nanoTime();
		//TODO kesobb
		//while(/*TODO*/) {
			tick();
		//}
	}
}
