import java.util.Random;
import java.awt.*;
import java.awt.image.*;
import javax.imageio.*;
import java.io.File;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : projlab
//  @ File Name : Ufo.java
//  @ Date : 2021. 03. 29.
//  @ Author : Levente Vigh
//
//


public class Ufo extends Entity implements IMine {

	public Ufo(Asteroid a) throws Exception {
		super(a);
		if(null == a)
			throw new Exception("Argument passed to Ufo.ctor is null!");
	}

	public Ufo() {
		super();
	}


		@Override
		public void paint(Graphics gr) {
				gr.setColor(Color.GRAY);
				gr.drawRect(posx, posy, (int)(10*scale),(int)(10*scale));
		}

	@Override
	public void move() throws Exception {
		Logger.call("Ufo.move()","");

		Place[] neighbours = (Place[]) position.getNeighbours().toArray();

		//veletlenszzeruen valasztunk egy uj helyet
		Random r = new Random();
		int nextIndex = r.nextInt() % neighbours.length;
		Place nextPosition = neighbours[nextIndex];

		moveTo(nextPosition); //felteszi magat az uj helyere

		Logger.ret("");
	}

	@Override
	public void solarStormEffect() {
		Logger.call("Ufo.solarStormEffect()","");
		Logger.ret("");
	}

	@Override
	public void explosionEffect() {
		Logger.call("Ufo.explosionEffect()","");
		Logger.ret("");
	}

	public void die() {
		Logger.call("Ufo.die()","");
		Logger.ret("");
	}

	public void mine() throws Exception {
		Logger.call("Ufo.mine()","");
		Material m = position.mineCore();
		if(null == m)
			this.move();
		Logger.ret("");
	}

	public void step() throws Exception {
		this.mine();
	}
}
