//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Uranium.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class Uranium extends Material {
	public void mined() {
	}
	
	public void nearSunEffect() {
	}
	
	private int getID() {
	}
}
