import java.util.Collection;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : WindowHandler.java
//  @ Date : 2021. 03. 19.
//  @ Author : 
//
//




public class WindowHandler {
	public void update(Collection<Asteroid> asteroidField) {
	}
}
